### ISSUE TITLE
Downloading more than 100 workouts results in duplicate entries

### ISSUE THREAD

**Issue by halfordfan** [justmedude/pylotoncycle#7]
I have 105 workouts in my Peloton account and am pulling them all down to drive a local dashboard and merge some metrics  with my Garmin Forerunner data.  I printed the workout dates out as details were retrieved and got the following output:

2021-01-21 16:27:56
2021-01-16 12:39:43
2021-01-16 11:35:18
2021-01-14 09:40:26
2021-01-09 09:23:08
2021-01-05 07:47:43
2021-01-04 16:32:10
2021-01-03 10:52:17
2020-12-31 08:47:55
2020-12-31 08:24:22
...
2020-06-16 09:17:03
2020-06-14 10:16:44
2020-06-13 12:31:26
**2021-01-05 07:47:43
2021-01-04 16:32:10
2021-01-03 10:52:17
2020-12-31 08:47:55
2020-12-31 08:24:22**

In the database, I use the date as the primary key and end up with only 100 workouts.  I noticed the dates in bold had been downloaded twice and as a result of using "REPLACE INTO" in mysql, no error was produced.

In GetWorkoutList, it appears that the limit value in the URL also determines the page size.  I replaced **range(0, pages)** with range(0, pages+1) and removed the section handling the calculate remainder value.  All workouts downloaded successfully.

**Comment by fainny** [comment]
@halfordfan I just came across this issue as well. Did you notice that the data only goes back so far? My first workout was 1/9/2020 and the data I pulled was only to 2/23/2020. 

Do you mind sharing the code you used to pull your workouts? I provided my code below; FYI I am using Alteryx to parse the json data.. 

Again, this does not pull the entire list of workouts for me and I have a number of duplicates. 

Any help would be appreciated.
```
import pylotoncycle

username = ""
password = ""
conn = pylotoncycle.PylotonCycle(username,password)
```
```
from ayx import Alteryx
import pandas as pd
workouts = conn.GetRecentWorkouts(conn.total_workouts)
```

```
import json
result = json.dumps(workouts)
df = pd.DataFrame(data=[result],columns=['dummy'])
Alteryx.write(df,1)
```

**Comment by halfordfan** [comment]
I used exactly the same call in my code that you use in yours.  Workouts are returned most recent first, so this bug will result in not getting your oldest workouts.

I've included the diff below with the changes I made to the class.

```
--- a/pylotoncycle/pylotoncycle.py
+++ b/pylotoncycle/pylotoncycle.py
@@ -75,7 +75,6 @@ class PylotonCycle:

         limit = 100
         pages = num_workouts // limit
-        rem = num_workouts % limit

         base_workout_url = \
             '%s/api/user/%s/workouts?sort_by=-created' % (
@@ -83,18 +82,13 @@ class PylotonCycle:

         workout_list = []
         current_page = 0
-        for i in range(0, pages):
+        for i in range(0, pages+1):
             url = '%s&page=%s&limit=%s' % (
                 base_workout_url, current_page, limit)
             resp = self.s.get(url, timeout=10).json()
             workout_list.extend(resp['data'])
             current_page += 1

-        if rem != 0:
-            url = '%s&page=%s&limit=%s' % (base_workout_url, current_page, rem)
-            resp = self.s.get(url, timeout=10).json()
-            workout_list.extend(resp['data'])
-
         return workout_list

```

**Comment by justmedude** [comment]
Thanks folks! If someone would like to submit a diff, I can accept it and push out a new version.

Thanks, and keep the bugs/fixes coming!

**Comment by justmedude** [comment]
Ok, I think I see the proper way to fix this. I'm checking in a new version. The difference is essentially:
```
diff --git a/pylotoncycle/pylotoncycle.py b/pylotoncycle/pylotoncycle.py
index 03c9bc1..229a55b 100755
--- a/pylotoncycle/pylotoncycle.py
+++ b/pylotoncycle/pylotoncycle.py
@@ -83,7 +83,8 @@ class PylotonCycle:

         workout_list = []
         current_page = 0
-        for i in range(0, pages):
+
+        if current_page < pages:
             url = '%s&page=%s&limit=%s' % (
                 base_workout_url, current_page, limit)
             resp = self.s.get(url, timeout=10).json()
```

**Comment by justmedude** [comment]
please take a look and verify that your use cases are fixed with this
thanks

**Comment by halfordfan** [comment]
That last diff will only work up to about ~200 workouts.  Without a loop, there's no way to get more than 2 pages.

I don't have 200 workouts, so I turned the limit down to 50 and started fetching all of my 109 workouts to verify full and partial pages.  I got the 59 of the most recent workouts with this change.  Same test with the previously proposed fixes fetched all 109.

**Comment by justmedude** [comment]
Ok, looks like I didn't have it as a while loop, so the new diff fixes that.
My initial testing looks good for the following values of workouts to fetch:
10 (which is what I fetch on a daily basis)
101
201

So, please check it out again. The tl;dr is what the `if` becomes a `while`

**Comment by halfordfan** [comment]
You've introduced a regression.  This is my output with the loop counter and the workout dates.

109 2021-01-31 09:42:12
108 2021-01-28 12:53:29
107 2021-01-26 08:02:34
106 2021-01-23 11:28:55
105 2021-01-21 16:27:56
104 2021-01-16 12:39:43
103 2021-01-16 11:35:18
102 2021-01-14 09:40:26
101 2021-01-09 09:23:08
100 2021-01-05 07:47:43
...
10 2020-06-19 11:07:54
**9 2021-01-05 07:47:43
8 2021-01-04 16:32:10
7 2021-01-03 10:52:17
6 2020-12-31 08:47:55
5 2020-12-31 08:24:22
4 2020-12-31 07:51:54
3 2020-12-29 09:27:51
2 2020-12-29 08:23:47
1 2020-12-26 10:55:03**

The problem is again on this line:   url = '%s&page=%s&limit=%s' % (base_workout_url, current_page, rem)
You're fetching the partial page with the remainder instead of the limit, which causes a smaller page size to be returned.  Page 2 of limit=100 is not the same as page 2 of limit=9.

I am not sure what is wrong with the fix that I checked in.  I don't have the time to continue to test and check in more changes for a bug that was fixed two days ago.

**Comment by justmedude** [comment]
The fix that you checked in broke use cases when fetching lower than the limit.

An example of where it broke is if you have 300+ workouts logged, but only wish to fetch 10. The results would have returned 100 (the limit).

**Comment by justmedude** [comment]
Also, while I understand you feeling annoyed, please know that I appreciate the opportunity to find additional ways to test out the code before I make a new release. I am closing in on the final fix.

**Comment by justmedude** [comment]
What what's it worth, and I appreciate you not wanting to deal more with this. I did get a final fix in that keeps the page limit size per request, but only returns the requested amount. The test I was running would output the date and then check for duplication in the date. So far, it seems good.
